name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK without Tests
      run: ./gradlew assembleDebug -x test # Build APK and skip tests

    - name: Create Release Directory
      run: mkdir -p CodeAssist-v3/build/outputs/release

    - name: Move APK to Release Directory
      run: mv CodeAssist-v3/build/outputs/apk/debug/app-debug.apk CodeAssist-v3/build/outputs/release/ || true # Move APK to release directory

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: CodeAssist-v3/build/outputs/release/*.apk # Adjust the path if necessary
