name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK without Tests
      run: ./gradlew build -x test # Build APK and skip tests
      
    - name: Move and Rename APK to Release Directory
      run: |
        # Move the APK to the release directory and rename it
        mv CodeAssist-v3/build/outputs/apk/debug/app-debug.apk CodeAssist-v3/build/outputs/release/app-debug.apk || true

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: CodeAssist-v3/build/outputs/release/app-debug.apk # Path to the renamed APK
